# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev*
      - feature/*
      - release/*

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          # Set your java version here
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew --build-cache build
      - name: Test with Gradle
        run: ./gradlew test
      - name: Publish to eldonexus
        run: ./gradlew publishMavenPublicationToEldoNexusRepository
        env:
          # Those credentials need to be set under "Settings -> Secrets -> Actions" in your repository
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
